spring:
  application:
    name: "trainersmanagement"
  datasource:
    url: jdbc:postgresql://localhost:5432/trainers_management
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        temp:
          use_sql_comments: true
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8087
