server:
  port: 8080
spring:
  application:
    name: "accounts"
  datasource:
    url: jdbc:postgresql://localhost:5432/accounts_management
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        temp:
          use_sql_comments: true
    hibernate:
      ddl-auto: create
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_URI_TOKEN}

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL}
  realm: ${KEYCLOAK_REALM}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  admin-username: ${KEYCLOAK_ADMIN_USERNAME}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD}

client-id: ${CLIENT_ID}
client-secret: ${CLIENT_SECRET}
grant_type: ${GRANT_TYPE}

logging:
  level:
    com.your.package.KeycloakFeignClient: DEBUG
