spring:
  application:
    name: accounts
  datasource:
    url: jdbc:postgresql://localhost:5432/accounts_management
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        temp:
          use_sql_comments: true
    hibernate:
      ddl-auto: create
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/trainingHubV1/protocol/openid-connect/certs"

keycloak:
  server-url: "http://localhost:7080"
  realm: "trainingHubV1"
  client-id: "client1"
  client-secret: "OiVCtHb3kgHQox0WJYjLtfhXPF5GtX9h"
  admin-username: "admin"
  admin-password: "admin"


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

logging:
  level:
    com.your.package.KeycloakFeignClient: DEBUG
